### ISSUE TITLE
Partition lines fail to snap at 0 area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-model-decimals#2]
@jonathanolson looks like I can only repro this in this sim, so maybe floating point errors?

1. Set up your horizontal area to have a left partition that is > 0.1 and < 0.6, like:

<img width="682" alt="screen shot 2018-04-16 at 3 30 04 pm" src="https://user-images.githubusercontent.com/5863899/38836367-17d65592-418b-11e8-8475-8d97ad35e7f3.png">

2. Using the pickers in the Dimensions panel (NOT the partition drag handle), decrease the horizontal area (slowly) until the right edge meets the partition line.

Usually the partition line would "snap" to the far edge when encountering an area of 0, but in this case it stays:

<img width="688" alt="screen shot 2018-04-16 at 3 29 50 pm" src="https://user-images.githubusercontent.com/5863899/38836366-17c41b48-418b-11e8-896d-a090146fd84c.png">

Seen on 10.13.3 Chrome, master at 3:00 PM (3/16).

**Comment by jonathanolson** [comment]
Yup, `0.5000000000000001`.

**Comment by jonathanolson** [comment]
Should be fixed in the above commit.

**Comment by phet-steele** [comment]
Looks fixed on my end.
