### ISSUE TITLE
Draggable node broken for keyboard nav

### ISSUE THREAD

**Issue by zepumph** [phetsims/area-model-decimals#5]
Although the area-model-introduction draggable node seems to work just fine, I get an assertion error when trying to use the arrow keys to change the grid size for the decimals sim. @jonathanolson do you know how this regression could have happened.

**Comment by jonathanolson** [comment]
There's a good chance that this may have never worked, unless you can point me to a case where it did?

I'll handle fixing it.

**Comment by zepumph** [comment]
That makes sense, we have just started using the keyboard fuzzer, so it is entirely possible that we have only just realized this. Thanks for taking it on.

**Comment by jonathanolson** [comment]
Ok, should be fixed with the above commit. However currently the "shift down delta" is the same as the "down delta". Should it be larger or smaller, and if so by how much?

**Comment by zepumph** [comment]
That is the same for other area model sims' draggable node interaction. For now it is probably fine to keep it like this, but in the end that is a design decision. By convention I think that the shift key is used to move in smaller steps most of the time, so likely there isn't a place for that here.

**Comment by zepumph** [comment]
I think we are ready to close if you think so.

**Comment by jonathanolson** [comment]
Sounds good, thanks!
